management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/tasktrackr
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet